services:
  cauta_database:
    image: postgres
    container_name: cauta_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"

  cauta_backend:
    build: .
    container_name: cauta_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cauta_database
    environment:
      DATABASE_HOST: cauta_database
      DATABASE_URL: ${DATABASE_URL}
      TZ: America/Sao_Paulo
    volumes:
      - .:/app

  cauta_redis:
    image: redis:latest
    container_name: cauta_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: