networks:
  dev_network: {}
services:
  vocalizeai_database_dev:
    image: postgres
    container_name: vocalizeai_postgres_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vocalizeai_dev
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    networks:
      - dev_network
  vocalizeai_backend_dev:
    build: .
    container_name: vocalizeai_backend_dev
    ports:
      - "8001:8000"
    env_file:
      - .env.dev
    depends_on:
      - vocalizeai_database_dev
    environment:
      DATABASE_HOST: vocalizeai_database_dev
      TZ: America/Sao_Paulo
      ENV_TYPE: dev
    networks:
      - dev_network
    volumes:
      - .:/app

  vocalizeai_redis_dev:
    image: redis:latest
    container_name: vocalizeai_redis_dev
    ports:
      - "127.0.0.1:6380:6379"
    networks:
      - dev_network
volumes:
  pgdata_dev: