services:
  vocalizeai_database:
    image: postgres
    container_name: vocalizeai_postgres
    volumes:
      - pgdata_main:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"

  vocalizeai_backend:
    build: .
    container_name: vocalizeai_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.main
    depends_on:
      - vocalizeai_database
    environment:
      DATABASE_HOST: vocalizeai_database
      TZ: America/Sao_Paulo
      ENV_TYPE: main
    volumes:
      - .:/app

  vocalizeai_redis:
    image: redis:latest
    container_name: vocalizeai_redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  pgdata_main: